InfoResourcesWebApplication/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InfoResourcesWebApplication;
using InfoResourcesWebApplication.Data;
using Microsoft.AspNetCore.Http;
using System.IO;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;

namespace InfoResourcesWebApplication.Controllers
{
    [Authorize(Roles = "admin, user")]
    public class ResourcesController : Controller
    {
        private readonly InfoResourcesWebApplicationContext _context;

        public ResourcesController(InfoResourcesWebApplicationContext context)
        {
            _context = context;
        }

        // GET: Resources
        public async Task<IActionResult> Index()
        {
            return View(await _context.Resource
                .Include(n => n.AuthorNavigation)
                .Include(n => n.TypeNavigation)
                .ToListAsync());
        }

        // GET: Resources/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource
                .Include(n => n.AuthorNavigation)
                .Include(n => n.TypeNavigation)
                .FirstOrDefaultAsync(m => m.ResourceId == id);
            if (resource == null)
            {
                return NotFound();
            }

            return View(resource);
        }

        // GET: Resources/Create
        public IActionResult Create()
        {
            var authors_list = new SelectList(_context.Author.ToList(), "AuthorId", "FullName");
            ViewData["authors_list"] = authors_list;
            var types_list = new SelectList(_context.ResourceType.ToList(), "ResourceTypeId", "ResourceTypeName");
            ViewData["types_list"] = types_list;
            return View();
        }

        // POST: Resources/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResourceId,ResourceName,UrlAddress,Type,Author,Annotation,AddDate")] Resource resource)
        {
            if (ModelState.IsValid)
            {
                Resource existingResource = await _context.Resource.SingleOrDefaultAsync(r =>
                (r.UrlAddress == resource.UrlAddress && r.UrlAddress != null) || r.ResourceName == resource.ResourceName);

                if (existingResource != null)
                {
                    ModelState.AddModelError(string.Empty, "This resource already exists in the base.");
                    var authors_list = new SelectList(_context.Author.ToList(), "AuthorId", "FullName");
                    ViewData["authors_list"] = authors_list;
                    var types_list = new SelectList(_context.ResourceType.ToList(), "ResourceTypeId", "ResourceTypeName");
                    ViewData["types_list"] = types_list;
                    return View(resource);
                }

                _context.Add(resource);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(resource);
        }

        // GET: Resources/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource.FindAsync(id);
            if (resource == null)
            {
                return NotFound();
            }
            var authors_list = new SelectList(_context.Author.ToList(), "AuthorId", "FullName");
            ViewData["authors_list"] = authors_list;
            var types_list = new SelectList(_context.ResourceType.ToList(), "ResourceTypeId", "ResourceTypeName");
            ViewData["types_list"] = types_list;
            return View(resource);
        }

        // POST: Resources/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResourceId,ResourceName,UrlAddress,Type,Author,Annotation,AddDate")] Resource resource)
        {
            if (id != resource.ResourceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(resource);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResourceExists(resource.ResourceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(resource);
        }

        // GET: Resources/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var resource = await _context.Resource
                .Include(n => n.AuthorNavigation)
                .Include(n => n.TypeNavigation)
                .FirstOrDefaultAsync(m => m.ResourceId == id);
            if (resource == null)
            {
                return NotFound();
            }

            return View(resource);
        }

        // POST: Resources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var resource = await _context.Resource.FindAsync(id);
            _context.Resource.Remove(resource);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index), nameof(Resource), new { id = resource.ResourceId, name = resource.ResourceName});
            return RedirectToAction(nameof(Index));
        }

        private bool ResourceExists(int id)
        {
            return _context.Resource.Any(e => e.ResourceId == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileCSV)
        {
            if (ModelState.IsValid && fileCSV != null)
            {
                using (var stream = new FileStream(fileCSV.FileName, FileMode.Create))
                {
                    await fileCSV.CopyToAsync(stream);
                    ImportFile(fileCSV, stream);
                }
                await _context.SaveChangesAsync();
                ViewData["ImportMessage"] = "File imported succefully.";
            } else
            {
                ViewData["ImportMessage"] = "Error while importing file: ";
                if (fileCSV == null)
                {
                    ViewData["ImportMessage"] += "file is null";
                } else
                {
                    var errors = ModelState.Where(x => x.Value.Errors.Any())
                   .Select(x => new { x.Key, x.Value.Errors });
                    ViewData["ImportMessage"] += "model state is invalid - " + errors;
                }                
            }

            //return RedirectToAction(nameof(Index));
            return View();
        }

        [NonAction]
        protected void ImportFile(IFormFile fileExcel, FileStream stream)
        {
            
            using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
            {
                foreach (IXLWorksheet worksheet in workBook.Worksheets)
                {
                    ResourceType type;
                    List<ResourceType> types = (from res in _context.ResourceType
                                where res.ResourceTypeName.Contains(worksheet.Name)
                                select res).ToList();

                    if (types.Count > 0)
                    {
                        type = types[0];
                    }
                    else
                    {
                        type = new ResourceType();
                        type.ResourceTypeName = worksheet.Name;
                        type.ResourceTypeDescription = "from EXCEL";
                        _context.ResourceType.Add(type);
                    }
                    
                    foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                    {
                        //try
                        {
                            Resource resource = new Resource();
                            resource.ResourceName = row.Cell(1).Value.ToString();
                            resource.Type = type.ResourceTypeId;
                            resource.UrlAddress = row.Cell(5).Value.ToString();
                            resource.Annotation = row.Cell(6).Value.ToString();

                            var add_date = row.Cell(7).Value.ToString();
                            if (add_date.Length > 0)
                            {
                                resource.AddDate = DateTime.Parse(add_date);
                            } else
                            {
                                resource.AddDate = DateTime.Now;
                            }
                            _context.Resource.Add(resource);

                            // Author
                            string authorName = row.Cell(2).Value.ToString();

InfoResourcesWebApplication/Views/Resources/Create.cshtml
@model InfoResourcesWebApplication.Resource

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Resource</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ResourceName" class="control-label"></label>
                <input asp-for="ResourceName" class="form-control" />
                <span asp-validation-for="ResourceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlAddress" class="control-label"></label>
                <input asp-for="UrlAddress" class="form-control" />
                <span asp-validation-for="UrlAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                @Html.DropDownListFor(m => m.Type, (IEnumerable<SelectListItem>)ViewData["types_list"])
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                @Html.DropDownListFor(m => m.Author, (IEnumerable<SelectListItem>)ViewData["authors_list"])
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Annotation" class="control-label"></label>
                <input asp-for="Annotation" class="form-control" />
                <span asp-validation-for="Annotation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddDate" class="control-label"></label>
                <input asp-for="AddDate" class="form-control" />
                <span asp-validation-for="AddDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoResourcesWebApplication/Views/Resources/Delete.cshtml
@model InfoResourcesWebApplication.Resource

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Resource</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResourceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResourceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeNavigation.ResourceTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorNavigation.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Annotation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ResourceId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InfoResourcesWebApplication/Views/Resources/Details.cshtml
@model InfoResourcesWebApplication.Resource

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Resource</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResourceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResourceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UrlAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UrlAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeNavigation.ResourceTypeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorNavigation.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Annotation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ResourceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InfoResourcesWebApplication/Views/Resources/Edit.cshtml
@model InfoResourcesWebApplication.Resource

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Resource</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ResourceId" />
            <div class="form-group">
                <label asp-for="ResourceName" class="control-label"></label>
                <input asp-for="ResourceName" class="form-control" />
                <span asp-validation-for="ResourceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlAddress" class="control-label"></label>
                <input asp-for="UrlAddress" class="form-control" />
                <span asp-validation-for="UrlAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                @Html.DropDownListFor(m => m.Type, (IEnumerable<SelectListItem>)ViewData["types_list"])
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                @Html.DropDownListFor(m => m.Author, (IEnumerable<SelectListItem>)ViewData["authors_list"])
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Annotation" class="control-label"></label>
                <input asp-for="Annotation" class="form-control" />
                <span asp-validation-for="Annotation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddDate" class="control-label"></label>
                <input asp-for="AddDate" class="form-control" />
                <span asp-validation-for="AddDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfoResourcesWebApplication/Views/Resources/Import.cshtml
@{
    ViewData["Title"] = "Import";
}

<h1>Export</h1>

<div>
    <p>
        @ViewData["ImportMessage"]
    </p>
 </div>
<p>To continue, return to <a href="/Resources/Index">Index</a>.</p>

InfoResourcesWebApplication/Views/Resources/Index.cshtml
@model IEnumerable<InfoResourcesWebApplication.Resource>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ResourceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ResourceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeNavigation.ResourceTypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorNavigation.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ResourceId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ResourceId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ResourceId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

<!-- Import -->
<div>
    <h3>Оберіть CSV-файл для завантаження</h3>
    @using (Html.BeginForm("Import", "Resources", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Завантажте CSV-файл:
            <input type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input type="submit" value="Завантажити" />
            </div>
        </div>
    }
</div>

<!--Export-->
<div>
    <h3>Вивантаження інформації в файл</h3>
    <a asp-action="Export">Вивантажити</a>
</div>